id: I3D3CFB25
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:30:47.860525+00:00
last_modified: 2022-12-14 10:30:47.860536+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-26T07:14:13.428Z'
  creationid: mabja
  eft-text-id: UT22084-068-016
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_282-Threefold_Training-v1
bases:
  CD23:
    source_metadata: null
    order: 1
    base_file: CD23.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
